// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYPZzdWgYb9DqSTzJAxqflNO2oR9Prb98',
    appId: '1:234919692297:web:bce23acee92bcd555810d8',
    messagingSenderId: '234919692297',
    projectId: 'atgevosystem',
    authDomain: 'atgevosystem.firebaseapp.com',
    storageBucket: 'atgevosystem.firebasestorage.app',
    measurementId: 'G-5Y58HT1V7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqRfpyw1dDwpNF60sAwcsFGKtImX3OQRg',
    appId: '1:234919692297:android:88ab1e466b2d432f5810d8',
    messagingSenderId: '234919692297',
    projectId: 'atgevosystem',
    storageBucket: 'atgevosystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdoibROTwjneYem5kOcSAahSm2Dq70Q-c',
    appId: '1:234919692297:ios:0d98a75c12cda2a05810d8',
    messagingSenderId: '234919692297',
    projectId: 'atgevosystem',
    storageBucket: 'atgevosystem.firebasestorage.app',
    iosBundleId: 'com.example.atgevosystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdoibROTwjneYem5kOcSAahSm2Dq70Q-c',
    appId: '1:234919692297:ios:0d98a75c12cda2a05810d8',
    messagingSenderId: '234919692297',
    projectId: 'atgevosystem',
    storageBucket: 'atgevosystem.firebasestorage.app',
    iosBundleId: 'com.example.atgevosystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYPZzdWgYb9DqSTzJAxqflNO2oR9Prb98',
    appId: '1:234919692297:web:fc4fc647d20860de5810d8',
    messagingSenderId: '234919692297',
    projectId: 'atgevosystem',
    authDomain: 'atgevosystem.firebaseapp.com',
    storageBucket: 'atgevosystem.firebasestorage.app',
    measurementId: 'G-WG03TDMMDK',
  );

}