const Map<String, String> tr = {
  'app_name': 'ATG Makina ERP',
  'app_name_demo': 'ATG Makina ERP (Demo)',
  'dashboard': 'Kontrol Paneli',
  'general_dashboard': 'Genel Kontrol Paneli',
  'crm': 'CRM',
  'crm_dashboard': 'CRM Kontrol Paneli',
  'production_dashboard': 'Üretim Kontrol Paneli',
  'purchasing_dashboard': 'Satınalma Kontrol Paneli',
  'finance_dashboard': 'Finans Kontrol Paneli',
  'bi_dashboard': 'BI Kontrol Paneli',
  'admin_dashboard': 'Yönetim Kontrol Paneli',
  'notifications': 'Bildirimler',
  'reports': 'Raporlar',
  'system_health': 'Sistem Sağlığı',
  'logout': 'Çıkış Yap',
  'login': 'Giriş Yap',
  'email': 'E-posta',
  'password': 'Şifre',
  'save': 'Kaydet',
  'cancel': 'İptal',
  'delete': 'Sil',
  'edit': 'Düzenle',
  'search': 'Ara',
  'add': 'Ekle',
  'update': 'Güncelle',
  'status': 'Durum',
  'active': 'Aktif',
  'inactive': 'Pasif',
  'customer': 'Müşteri',
  'customers': 'Müşteriler',
  'quote': 'Teklif',
  'quotes': 'Teklifler',
  'invoice': 'Fatura',
  'invoices': 'Faturalar',
  'payment': 'Tahsilat',
  'payments': 'Tahsilatlar',
  'order': 'Sipariş',
  'shipment': 'Sevkiyat',
  'inventory': 'Stok',
  'production': 'Üretim',
  'supplier': 'Tedarikçi',
  'suppliers': 'Tedarikçiler',
  'purchase_order': 'Satınalma Emri',
  'settings': 'Ayarlar',
  'modules': 'Modüller',
  'permissions': 'Yetkiler',
  'admin': 'Yönetici',
  'superadmin': 'Süper Yönetici',
  'success': 'Başarılı',
  'error': 'Hata',
};

String trText(String key) => tr[key] ?? key;
